import './globals.css';
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Providers from './components/Providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
